### ISSUE TITLE
A few questions ....

### ISSUE THREAD

**Issue by ColinEberhardt** [ballercat/walt#11]
This is a really interesting idea. As a JavaScript developer, I also got quite frustrated with having to use C / C++ to create WebAssembly. I also dislike the extra 'baggage' that tools like Emscripten introduces to the code you generate.

Anyhow, I was wondering how your solution compare to [AssemblyScript](https://github.com/AssemblyScript/assemblyscript)? I am guessing that you want to keep it close to the WebAssembly 'metal', so would not plan to introduce objects, classes, etc ... ?

I do wonder whether it would be worth creating your own TypeScript subset for this project? I notice you are using a TypeScript-style type annotation.

Anyhow, good luck with this project!

**Comment by ballercat** [comment]
Hello, thanks for tacking a look!

I did notice AssemblyScript as I began the project, but the idea of extra layers of abstraction were not appealing to me. I've also explored a C to WASM but that felt clunky and I abandoned the idea.

My main goal is to just write WebAssembly, with a friendlier syntax. WebAssembly has higher-level constructs than traditional assembly languages, but that text format can be a pain to write in. The freedom and control over the final wasm output is very appealing to me. JavaScript _with rules_ just seemed like a good sweet-spot for what I wanted to do.

As for the TypeScript-type annotation. I actually took that idea from [flow](https://flow.org/), which I am familiar with and use in the project itself. I think it's a nice option for mimicking the type system of WebAssembly. Hopefully I can figure out a way to not require annotations at all _one day_. But it's a delicate balance, like how do you treat type conversions etc., 

On the subject of classes and objects. I definitely want an object literal-like syntax as that would help tremendously. I think there are solid ways of implementing objects without any compiler magic. No plans for implementing classes though!

Thanks for the shoutout!

**Comment by ColinEberhardt** [comment]
Thanks for the clarification, the project goals are quite different to AssemblyScript.

I honestly believe that for WebAssembly to really take off there need to be better tools for JavaScript developers who want to create wasm modules. This project, AssemblyScript, TurboScript are all really great steps in that direction.
