### ISSUE TITLE
no walt-cli on npm? how to install walt-cli?

### ISSUE THREAD

**Issue by jeromeetienne** [ballercat/walt#122]
## Overview
`walt-cli` isnt available via npm. here is a link to npmjs.com to check https://www.npmjs.com/search?q=walt-

## Expected
```npm install walt-cli``` should find and install the package

## Actual
```npm install walt-cli``` results in a not found. ```npm ERR! 404 Not Found: walt-cli@latest```

**Comment by jeromeetienne** [comment]
after discussing on twitter, @ballercat mentioned walt-cli wasnt ready enougth to be published at the moment. https://twitter.com/ballercat/status/1010169416208846848

**Comment by jeromeetienne** [comment]
@ballercat my personnal goal is simply to output a .wasm that i can load on my own. 

All the webpack stuff doesn't match my need.

I would like to use walt to produce fast computer vision code. i do augmented reality libraries in the browser, so fast way to run in browser is good for me :)

**Comment by ballercat** [comment]
Neat, I've been looking at AR in the browser and it seems like a great opportunity to utilize WebAssembly. I'll have to take a closer look at your projects!

Okay so back to your use-case. Yes the cli will be able to do this for you eventually, for now it's possible to use the JS API directly with the `walt-compiler` package. There is an example of this in #86 where the default compiler export takes a .walt source and spits out a buffer of a wasm program. You may write this to a file of your choosing.

The reason why the cli is not out is that it will include automated linking of .walt modules together, which ended up being a bit more complex than I first imagined. But even that is also possible today with the JS APIs of the `walt-link` package, seen here https://github.com/ballercat/walt/tree/master/packages/walt-link . It's used internally in the compiler itself to build some walt-only specs.

**Comment by jeromeetienne** [comment]
got it! so as i understand it, walt-cli should work but a single .walt, correct ?

i guess i will just install yours current version locally and modify it if needed. 

i love the idea to be able to generate webassembly at the 'assembly' level. with a syntax/grammar way more friendly than S expressions. thanks for doing this work 👍 

https://github.com/jeromeetienne/ar.js is the library im working on

**Comment by ballercat** [comment]
An MVP of the cli was published as part of #116
