### ISSUE TITLE
Canvas example breaks if `canvas` button is not selected before pressing play

### ISSUE THREAD

**Issue by JobLeonard** [ballercat/walt#127]
## Expected
Explorer should switch to `Canvas` tab and show bouncing particles

## Actual
![image](https://user-images.githubusercontent.com/259840/42450151-7967ae8e-8383-11e8-89df-9387d861d76a.png)

## Suggested Fix

Perhaps mounting all the tabs in React, but hiding them via CSS?

**Comment by ballercat** [comment]
Yeah, this has always been an issue. Switching to the correct tab would probably be best.
