### ISSUE TITLE
exporting of declared memory

### ISSUE THREAD

**Issue by poeticAndroid** [ballercat/walt#130]
# Bug Report
## Overview
Exporting memory from Walt doesn't seem to work right..

## Expected
The wasm module should be able to instantiate and export the memory..

## Actual
    CompileError: WasmCompile: Wasm decoding failed: global index 4294967295 out of bounds (0 entries) @+24

## Example
    export const memory: Memory = { initial: 1 };

**Comment by ballercat** [comment]
Good catch. The Memory & Table type exports are not handled per spec currently 

> Note that, in the MVP, the only valid index value for a memory or table export is 0.

Should be able to patch it shortly.
