### ISSUE TITLE
visual glitch on bounce

### ISSUE THREAD

**Issue by YopSolo** [ballercat/walt#14]
in examples\walt\animation.walt

change
export function onInit(totalParticles: i32): void {
  width = 500;
  height = 300; // visual glitches appears with a lot of particles
  total = totalParticles;

by

export function onInit(totalParticles: i32): void {
  width = 500;
  height = 400; //match the real canvas height 
  total = totalParticles;

**Comment by ballercat** [comment]
Thanks, I was wondering why this was happening 👍
