### ISSUE TITLE
This issue will self close. Thank you.

### ISSUE THREAD

**Issue by innerop** [ballercat/walt#155]
Thank you for making this wonderful tool.

I see a lot of haters on HN asking why it exists or suggesting that it shouldn't exist because somehow AssemblyScript has really annoying fans. 

Keep it up!

**Comment by ballercat** [comment]
Thank you for the words of support. It really means a lot.

**Comment by thomassturm** [comment]
I'd like to co-sign this post/issue. Thanks for all the great work in making Walt. It's been a while that I've contributed since life got in the way, but I'm still following along. This is a very promising project and I'm telling everybody about it. :)
