### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by alex-dixon** [ballercat/walt#17]
Hi. This seems like a great project! 

What would you think about adding a roadmap or something in the readme about your goals? Might help contributors know where you want to go and where you don’t. 

Eg, if the language you’re after isn’t really JavaScript but a version of it, maybe single line comments on multiple lines are fine. 😊

**Comment by ballercat** [comment]
Hi. Thank you.

I think adding a roadmap is a priority at this point. I'd like to get some contributions for sure. I don't think I anticipated this level of interest so quickly, so documentation has fallen behind. I'll leave the issue open until I write one up. If you have any suggestions or examples of good roadmap formats on github, that would be helpful!

**Comment by styfle** [comment]
@ballercat Here's a good example of a Roadmap: [TypeScript/wiki/Roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap)

**Comment by ballercat** [comment]
Thanks for the suggestion.

Initial Roadmap is up on the [Wiki](https://github.com/ballercat/walt/wiki/Roadmap) and linked from the readme.
