### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by coder0107git** [ballercat/walt#187]
It seems that this project hasn't had any activity in a while. Although the last commit was just from last January, there's hardly been any activity since 2019 [[1]](https://github.com/ballercat/walt/commits/master/) [[2]](https://github.com/ballercat/walt/graphs/code-frequency). It seems all of the small compile to WASM projects have died. I've come across many javascript-like language to webassmbly projects that have died. I was hoping to use this in a small project but am not sure if I should since this seems to be dead. [AssemblyScript](https://www.assemblyscript.org/) went dormant until some new developers got on board. Assemblyscript looks nice to use but every time I've used it it feels like I'm battling the tooling. [Javy](https://github.com/bytecodealliance/javy) doesn't seem very well documented, my expiraments with it have ended poorly, and it doesn't seem active. [Grain](https://grain-lang.org/) has become a faintly javascript tinted functional language, nothing like it's original javascript-friendly syntax. This project seems very nice but seems to have died. Is this project dead?

**Comment by ballercat** [comment]
It's not "dead" per-se, I think "dormant" is fair though. It's a side-project after all. I've been meaning to go back to it here and there to implement new parts of the WebAssembly spec. 

Please note though that I would discourage you from building anything particularly complex with it even if I was actively contributing on the daily basis. I've built this to learn wasm and compilers, which I did, but it's no where near a fully featured language with proper tooling and documentation.

If you are exploring wasm I honestly would recommend using something like Zig instead https://ziglang.org/. It's an excellent 
language and has WebAssembly support.

Good luck!

**Comment by coder0107git** [comment]
Okay. Thanks for the information!
