### ISSUE TITLE
Comments support

### ISSUE THREAD

**Issue by ballercat** [ballercat/walt#2]
# Goal

Support comments in source code

* `//`
* `/* */`

# Problem

The tokenizer does not skip comments, it should. These won't be compiled into final binary but can be useful for debugging purposes.

**Comment by artemruts** [comment]
I can try to do this. Something easy to start with 👍

**Comment by ballercat** [comment]
Not sure where you are at with this but I added `//` single line comments in `0.0.2`. Still need multi-line comments though.

**Comment by iddan** [comment]
Might be good to define a standard docs format as a convention as well. JSDoc is just one option

**Comment by whitecrownclown** [comment]
I've started working on this, adding multi-line comments.

**Comment by ballercat** [comment]
@whitecrownclown

`Syntax.Comment` is undefined, could you patch it as part of your changes? Thanks.

**Comment by whitecrownclown** [comment]
@ballercat Sure, i'll keep that in mind.

**Comment by iddan** [comment]
If it's done shouldn't it be closed?
