### ISSUE TITLE
Records Semantics instead of Objects

### ISSUE THREAD

**Issue by iddan** [ballercat/walt#22]
As strings has nothing to do with the lookup and usage of the actual compiled result of objects I think it's better to use tokens (like in ReasonML) and not mention strings whatsoever

**Comment by ballercat** [comment]
You are suggesting that we don't use string for object properties?

If you are, I agree. Strings were just the quickest way for me to support them without a ton of effort 🙃 

Supporting token-based property names would require:

- [ ] The dot `.` operator which is not currently supported. We would need the tokenizer to recognize it (easy) and for the parser to convert it down to a plain old array subscript.
- [ ] Unit tests
- [ ] Removing/converting string property lookups, in examples and tests.

I would totally accept a PR or two that made this happen.

**Comment by ballercat** [comment]
I'm going to close this in favor of #28

Thanks again.
