### ISSUE TITLE
Object Spread operator

### ISSUE THREAD

**Issue by iddan** [ballercat/walt#23]
I think this is a low hanging fruit once you have objects and merging work right. Basically a `{ a: 2, ...obj }` should be transformed to `merge({ a: 2 }, obj)` and there should be no comma after the spread operator

**Comment by ballercat** [comment]
Seems reasonable and useful.

Would require the `...` operator support, which _will_ get difficult. As then it would be reasonable to support syntax like 

```js
const { x, y } = vector;
// and
const [x, y] = vector;
```

as well as some other ES6 goodies, like destructuring function parameters. This is by no means an easy thing to get right, but super useful to have.

A change like this will require a ton of testing.

**Comment by iddan** [comment]
I think it's more important to support { ...x, } support before destructing assignment
