### ISSUE TITLE
Is there a mapping between wasm bytecodes and Javascript keywords?

### ISSUE THREAD

**Issue by piranna** [ballercat/walt#26]
This would allow to exactly know what bytecodes are still missing to be implemented and where contributions can be done :-) Also this would allow to diferenciate what Javascript features would be considered native code and what can be added as sugar-sintaxis or runtime library to have a full Javascript implementation :-)

**Comment by ballercat** [comment]
Hi.

I like the idea of enumerating what can be _native_ code. I think I'm going to bundle this into documentation/roadmap. I feel like it'll be useful not only for outside contributors but myself as well as a good exercise in planning a roadmap.

 Thanks.

**Comment by piranna** [comment]
You are welcome :-) Yes, a roadmap would be great! :-D
