### ISSUE TITLE
Bitwise Operators

### ISSUE THREAD

**Issue by ballercat** [ballercat/walt#33]
# Goal
Should be able to do bitwise math

# Overview
Binary operators are pretty solid now, but bitwise opcodes are not generated currently. Pretty straightforward change. Nothing should change in the parser, might be as easy as adding it to https://github.com/ballercat/walt/blob/master/src/emitter/opcode.js#L262

# Acceptance Criteria
* Unit Test every binary bitwise opcode
* Tests pass

**Comment by novoselrok** [comment]
Hey, I would love to help with this if possible :)

**Comment by ballercat** [comment]
Of course, help is appreciated. Looking forward to the PR
