### ISSUE TITLE
Error when using i64 values in functions

### ISSUE THREAD

**Issue by novoselrok** [ballercat/walt#40]
## Overview

I get a compiler error when trying to use i64 type values in functions (assigning them to variables, or returning from functions).

When I try to compile this:
```
const x: i64 = 42;
```
everything works fine.

But, if this line is in a function:
```
function test(): void {
	const x: i64 = 42;
}
```
I get the following error:

```
CompileError: wasm validation error: at offset 27: type mismatch: expression has type i64 but expected i32
```

**Comment by ballercat** [comment]
Thanks.

Looks like locals are not emitted correctly for `i64` variables.

```
00000027:                1 ; function count
00000028:                c ; body size in bytes
00000029:                1 ; locals count
0000002a:                1 ; number of locals of following type
0000002b:               7f ; i32
```

Probably some older code I did not bother to fully test, should be easy enough to fix/test.
