### ISSUE TITLE
Documentation: Getting started.

### ISSUE THREAD

**Issue by ballercat** [ballercat/walt#44]
Documentation is slim, the following needs to be done to help with that:

* There need to be some "Getting started" documentation.
* There needs to be an npm module for simple installation
* `raw-loader` with the compiler example, like in the `/docs`

**Comment by thomassturm** [comment]
Hey - just realized that you've got an issue open for this. I just wrote up a simple set-by-step guide to get a minimal Walt project going: https://github.com/thomassturm/walt/wiki/Walt-Mini-Tutorials

Feel free to include it in your Wiki or whereever it makes sense.

**Comment by ballercat** [comment]
Hey, this is excellent! Short and sweet, which is what I would expect from a simple getting started tutorial.

I think you should go ahead and post it on the Wiki in this repo. Let me know if you can't, maybe I have some setting which is not allowing others to post.

Also if you want to document anything else and need more info just let me know. I would be happy to help.

**Comment by thomassturm** [comment]
I'd be happy to add it to the main Walt wiki, but can't figure out how. There must be a setting where you can open it up for outside editors. Or you could just cut & paste it over from my Wiki, I guess.

**Comment by ballercat** [comment]
You were right. I adjusted the settings, should be good to go 👍

**Comment by thomassturm** [comment]
Ah! I see the edit button now. I'm going in. :)

**Comment by thomassturm** [comment]
OK. Check it out. No idea how to sort the little sidebar menu. ¯\_(ツ)_/¯

**Comment by ballercat** [comment]
Looks good. It's okay if it's not sorted, I'm not super worried about it. These will eventually roll into the work @matteocargnelutti is doing for a static site generator in #59
