### ISSUE TITLE
Improve styles for Walt Playground/Explorer

### ISSUE THREAD

**Issue by hamlim** [ballercat/walt#5]
Opening an issue to track some work on improving the styles for the interactive playground.

Some initial questions for @ballercat:

* Do you still want the Material Design styles/javascript?
* Any preference on a color theme? Even just a primary and secondary color?

**Comment by ballercat** [comment]
Thanks @hamlim 

The simple answer is I don't have a preference on the style or how the UI is implemented. So you have full artistic freedom here.

* I have no preference.
* Hmm I think right now it pretty ugly so anything would be better. A lighter color scheme would be nice, but we might be limited by what color schemes ace editor provides. More pastel colors would be nice. 

I kind of like this type of layout for the side-by-side editor and disassembler output https://dribbble.com/shots/1179893-Pixem-A-PX-to-EM-Converter

I like this palette https://dribbble.com/shots/2052852-OpenWeather-Beta, for example, **but no real preference.**

I don't have a logo currently but I was thinking of making it a play on ["JS/WA" from web assembly logo](http://www.i-programmer.info/images/stories/News/2017/mar/A/jswasm.jpg). Without JS and with italic _"lt"_ font to the right of it in yellow. So I'd love to see a touch of yellow thrown in.

But again, do what you can. A nice Layout with labels for Disassembler and Console output would be a huge.

**Comment by hamlim** [comment]
Cool I will start with these dribbble links and see what I can drum up.  👍

**Comment by hamlim** [comment]
Alright, I have some initial work done, need to polish up some of the styles but can probably get an example up tomorrow to check out.

**Comment by ballercat** [comment]
Good stuff @hamlim, looking forward to it!
