### ISSUE TITLE
npm distribution of compiler version mismatch

### ISSUE THREAD

**Issue by thomassturm** [ballercat/walt#68]
The file walt/packages/walt-compiler/dist/walt.min.js is significant older than the non-minified version of the compiler. 

The npm download of the compiler does not currently function since it seems several method names don't even exist in the minified version of the file.

**Comment by ballercat** [comment]
Hey, thanks for reporting this.

These minified builds must be ancient as I don't even recall building them. I'll publish a fix sometime today.

**Comment by ballercat** [comment]
Should be resolved now. The new package is published with a minified build 👍
