### ISSUE TITLE
Expose memory.grow, memory.size, memory.dataLength

### ISSUE THREAD

**Issue by ballercat** [ballercat/walt#79]
# Goal
Unblock work for a full-blown allocator.

## Overview
`memory_grow` are not available through walt, but can be implemented as members of the `Memory` and `Table` types.

## Acceptance Criteria

This should work

```js
const memory : Memory = { initial: 1 };

function test() {
  memory.size();
  memory.grow();
  memory.dataSize();
}
```

- [x] `Memory.grow()`
- [x] `Memory.size()` current size of memory
- [x] `Memory.dataSize` length of the data section, always zero until data senction encoding is implemented.

**Comment by xtuc** [comment]
Just FYI https://github.com/WebAssembly/spec/pull/649

**Comment by ballercat** [comment]
Thanks, hopefully, it only affects text encoding. Might need to adjust some docs etc.,

**Comment by poeticAndroid** [comment]
this would be nice :)

**Comment by ballercat** [comment]
Implemented by #148

**Comment by JobLeonard** [comment]
Thanks, good to know (that kind of sucks for the things that I was thinking of doing though, because it involves operations on arrays that can get quite big but only incidentally)

**Comment by poeticAndroid** [comment]
you can always reuse the memory for other stuff..
